### ISSUE TITLE
excel datasheets with duplicated names will result in the same file id.

### ISSUE THREAD

**Issue by yzuuang** [MI-FraunhoferIWM/data2rdf#10]
- for the `csv` file, it will generate md5 according to the content ( [this line](https://github.com/MI-FraunhoferIWM/data2rdf/blob/main/data2rdf/csv_parser.py#L140) ), 
- but for `excel` file, it will generate sha256sum according to the file path ( [this line](https://github.com/MI-FraunhoferIWM/data2rdf/blob/main/data2rdf/excel_parser.py#L236) ). So different datasheets with duplicated names will result in the same file ID.

**Comment by MBueschelberger** [comment]
Starting from v2.0.0, we do not create generate uids for the files anymore, since the output is only written to disk on demand,
