### ISSUE TITLE
Add exception for pre-commit to avoid repetition of test_utils

### ISSUE THREAD

**Issue by deepukr007** [MI-FraunhoferIWM/data2rdf#11]
Having the file tes_utils.py outside the folder and importing it is causing pre-commit to fail with the below error

tests/csv_pipeline_test/test_csv2rdf.py:8:1: E402 module level import not at top of file

[104](https://github.com/MI-FraunhoferIWM/data2rdf/actions/runs/4756903657/jobs/8453077798#step:4:109)from test_utils import check_file_identifier_in_folder

https://github.com/MI-FraunhoferIWM/data2rdf/actions/runs/4756903657/jobs/8453077798

**Comment by MBueschelberger** [comment]
Unit tests have been re-structured since v2.0.0.
