### ISSUE TITLE
use data without column data

### ISSUE THREAD

**Issue by THuschle** [MI-FraunhoferIWM/data2rdf#15]
The pipeline is designed to convert files that contain meta data and tabular data (column data). 
Some use cases don't provide any tabular data in the input dataset. If there is no link to tabular data in the location mapping, there is a error message, also if the linked location doesn't exist. 

The workaround for now is to generate some dummy tabular data in a additional worksheet. The resulting hdf5 file will just be ignored.

Is it possible to enable the conversion of only meta data?

Example file with additional worksheet for dummy array.
[  16MnCr5 (6).xlsx](https://github.com/MI-FraunhoferIWM/data2rdf/files/10863408/16MnCr5.6.xlsx)

**Comment by MBueschelberger** [comment]
This has been covered since v2.0.0.
