### ISSUE TITLE
Mapping to Method not successfully 

### ISSUE THREAD

**Issue by THuschle** [MI-FraunhoferIWM/data2rdf#16]
**What is the issue**

When using Pandas 1.5.3, instances are not correctly mapped as described in the method graph / mapping.xlsx instead there is a additional instance generated. 
Therefore there are two instances: one with the the data and one with the value that are not connected.
![grafik](https://user-images.githubusercontent.com/86046865/222164863-7f9be90a-0fcd-4fc6-bc13-41bf7404970a.png)

**How to solve**
The issue doesn't occure when using Pandas 1.1.5 but this won't be supported in Python 3.10.
Investigate what are the differences between the versions and how/why they effect the mapping of instances.

**How should the solution look like**
The result should look the same as it already is with pandas 1.1.5.
![grafik](https://user-images.githubusercontent.com/86046865/227176694-20b13966-4fc9-4131-8d61-99ed37888f5a.png)

**Comment by MBueschelberger** [comment]
Starting from v2.0.0, we are using pandas =>2,<3 and the method graph is optional. Hence I will close this issue.
