### ISSUE TITLE
Create instances based on tabular data

### ISSUE THREAD

**Issue by THuschle** [MI-FraunhoferIWM/data2rdf#17]
Currently the data2rdf pipeline has just the option to create instances for the as metadata described data of the inputfile and store the columndata in hdf5.
In some use cases it is also relevant to create instances for tabular data. e.g. KupferDigital provides as input a series of measurements stored values in a tabular format. Import is to keep the links of the values e.g. all values of one line are linked to each other (position in x and y to the hardness value)
[ExampleData.xlsx](https://github.com/MI-FraunhoferIWM/data2rdf/files/10863270/ExampleData.xlsx)

@yzuuang

**Comment by MBueschelberger** [comment]
This is supported now since ~ v2.0.0.

See:
https://data2rdf.readthedocs.io/en/latest/examples/abox/6_custom_relations.html
