### ISSUE TITLE
Make internal mappings of the unit/quantity relations human-readable (or make mapping flexible)

### ISSUE THREAD

**Issue by MBueschelberger** [MI-FraunhoferIWM/data2rdf#27]
If we look at the output of the `merged_graph.ttl`, we see that were are some hardcoded EMMO-relations which are not human-readable and the IRIs are not resolvable:
```
fileid:numeric-12 a ns5:EMMO_4ce76d7f_03f8_45b6_9003_90052a79bfaa ;
    ns5:EMMO_faf79f53_749d_40b2_807c_d34244c192f4 "80.0"^^xsd:float ;
    ns3:EMMO_67fc0a36_8dcb_4ffa_9a43_31074efa3296 fileid:unit-12,
        fileid:unitliteral-12 .
```

I would be good to include either the [`emmo-renamed.ttl`](https://emmo-repo.github.io/versions/1.0.0-beta4/emmo-renamed.ttl) with the renamed labels or include a mechanism that provide a custom pattern to generate subgraphs for the units and quantity representations (e.g. for with another ttl-template).

**Comment by yoavnash** [comment]
Related to #43

**Comment by MBueschelberger** [comment]
Starting from v2.0.0, we do not use EMMO units anymore but refer to QUDT.
