### ISSUE TITLE
Add Graph Identifier

### ISSUE THREAD

**Issue by MBueschelberger** [MI-FraunhoferIWM/data2rdf#29]
In [this line](https://github.com/MI-FraunhoferIWM/data2rdf/blob/ccbe5b0950b0b221b9274ca82971a577d82a4721/data2rdf/annotation_pipeline.py#L222), we need a graph identifier in order to have a reference for fetching the subgraph in the SDK later on. 

The simplest fix would be to use the [`base_iri`](https://github.com/MI-FraunhoferIWM/data2rdf/blob/ccbe5b0950b0b221b9274ca82971a577d82a4721/data2rdf/annotation_pipeline.py#L49) which is passed to the `AnnotationPipeline`, .e.g. like this:

```
graph = Graph(identifier=self.base_iri)
```

**Comment by pdr-z** [comment]
Related to: item 4 in [Data2RDF Next](https://github.com/MI-FraunhoferIWM/data2rdf/issues/28#issue-1887718500) issue:

**Comment by pdr-z** [comment]
Expected to need to alter graph creations else-where too in order to support context, however the suggested simple fix seems to be all

**Comment by pdr-z** [comment]
Expected to need to alter graph creations else-where too in order to support context, however the suggested simple fix seems to be all
