### ISSUE TITLE
Relax requirements on dependecies

### ISSUE THREAD

**Issue by yoavnash** [MI-FraunhoferIWM/data2rdf#30]
The requirements on the dependencies are too strict. For example, [SQLAlchemy](https://github.com/MI-FraunhoferIWM/data2rdf/blob/main/setup.cfg#L29) must be v1.4.46 which is unsafe according to the [safety](https://pypi.org/project/safety/) tool.

The requirements should be relaxed by specifying allowed range of versions. See here an example:
https://github.com/materials-marketplace/python-sdk/blob/main/setup.cfg#L22

**Comment by deepukr007** [comment]
Added data2rdf dependency to knowledge service , build is failing due to SQLAlchemy version conflict between knowledge service and data2rdf. 

```
#0 7.276 The conflict is caused by:
#0 7.276     The user requested SQLAlchemy==2.0.25
#0 7.276     alembic 1.13.1 depends on SQLAlchemy>=1.3.0
#0 7.276     data2rdf 1.0.3 depends on sqlalchemy==1.4.46
#0 7.276 
#0 7.276 To fix this you could try to:
#0 7.276 1. loosen the range of package versions you've specified
#0 7.276 2. remove package versions to allow pip attempt to solve the dependency conflict
```
