### ISSUE TITLE
Create merged graph in the example

### ISSUE THREAD

**Issue by yoavnash** [MI-FraunhoferIWM/data2rdf#31]
The [example file](https://github.com/MI-FraunhoferIWM/data2rdf/blob/main/examples/pipeline_demo.ipynb) is missing the creation of the merged graph:

```
merged_graph = os.path.join(output_folder, 'merged_graph.ttl')
pipeline.export_ttl(merged_graph)
```

Also, to make it more instructive, a text block could be added at the end to explain what was generated (e.g., the hdf5 files)

**Comment by MBueschelberger** [comment]
v2.0.0 directly delivers an rdflib Graph which can be serialized and printed within the notebook.
