### ISSUE TITLE
Support linking to external data sources

### ISSUE THREAD

**Issue by yoavnash** [MI-FraunhoferIWM/data2rdf#52]
At the moment, linking the generated RDF to external data sources is only possible for the time series data that is provided in the input data file. However, in some cases, the data can be coming from an external data source (e.g., GrantaMI database) which doesn't appear in the CSV/excel file. There should still be a way to create linkes to it from the RDF. Perhaps the mapping file format could be extended to support this functionality.

**Comment by MBueschelberger** [comment]
With k8s, we are able to fetch resources as a json and use it within the next step as an input for data2rdf, which supports json files starting from v2.0.0. Hence I close this issue, since k8s has a larger flexibility for handling secrets etc for this connection.
